# Generated by Django 4.1.6 on 2023-02-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xato',
            name='notogri',
            field=models.CharField(default='hato', max_length=50),
            preserve_default=False,
        ),
    ]
